# Generated by Django 5.0.6 on 2024-06-13 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otb', '0003_reserva_e_reserva_reserva_nombre_reserva_rut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejecutivo',
            old_name='usuario',
            new_name='n_usuario',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_genero',
        ),
    ]
