# Generated by Django 5.0.6 on 2024-06-15 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('otb', '0004_rename_usuario_ejecutivo_n_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='nombre',
        ),
        migrations.DeleteModel(
            name='Ejecutivo',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
