# Generated by Django 5.0.6 on 2024-06-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('otb', '0005_remove_reserva_rut_remove_reserva_nombre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('aPaterno', models.CharField(max_length=30)),
                ('aMaterno', models.CharField(max_length=30)),
                ('fono', models.IntegerField()),
                ('edad', models.IntegerField()),
                ('deposito', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
            ],
        ),
    ]
